# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install apache-beam torch transformers qdrant-client
      - name: Run Beam pipeline (test)
        run: |
          python data_ingestion/beam_pipeline.py || true
      - name: Run intent classifier (test)
        run: |
          python intent_rag_backend/intent_classifier.py
      - name: Run model training (test)
        run: |
          python model_training/finetune.py
      - name: Export models (test)
        run: |
          python compilation/export.py
